"""
pyknock/report.py
─────────────────
Generate human-readable Markdown + JSON reports from AgentState.
"""

from __future__ import annotations
import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path

from agent import AgentState, Finding


# ─────────────────────────────────────────────────────────────
# Severity ordering
# ─────────────────────────────────────────────────────────────

SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
SEV_EMOJI = {"CRITICAL": "💀", "HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢", "INFO": "ℹ️"}


def _sort_findings(findings: list[Finding]) -> list[Finding]:
    return sorted(findings, key=lambda f: SEV_ORDER.get(f.severity.upper(), 99))


def _sev_counts(findings: list[Finding]) -> dict[str, int]:
    counts: dict[str, int] = {k: 0 for k in SEV_ORDER}
    for f in findings:
        key = f.severity.upper()
        counts[key] = counts.get(key, 0) + 1
    return counts


# ─────────────────────────────────────────────────────────────
# Markdown report
# ─────────────────────────────────────────────────────────────

def generate_markdown(state: AgentState) -> str:
    now     = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    elapsed = time.time() - state.start_time
    dur_str = f"{int(elapsed // 60)}m {int(elapsed % 60)}s"
    sorted_f = _sort_findings(state.findings)
    counts   = _sev_counts(state.findings)

    lines: list[str] = [
        "# 🔓 PyKnock Penetration Test Report",
        "",
        f"> Generated by **PyKnock v1.0.0** — Autonomous AI Pentesting Agent  ",
        f"> Report Date: **{now}**",
        "",
        "---",
        "",
        "## 📋 Executive Summary",
        "",
        f"| Field        | Value |",
        f"|:-------------|:------|",
        f"| Target       | `{state.target}` |",
        f"| Scan Started | {datetime.fromtimestamp(state.start_time).strftime('%Y-%m-%d %H:%M:%S')} |",
        f"| Duration     | {dur_str} |",
        f"| AI Cycles    | {state.iterations} |",
        f"| Tools Run    | {len(state.tools_run)} |",
        f"| Open Ports   | {', '.join(state.open_ports) or 'none detected'} |",
        "",
        "### Finding Counts",
        "",
        "| Severity | Count |",
        "|:---------|------:|",
    ]
    for sev, count in counts.items():
        emoji = SEV_EMOJI.get(sev, "•")
        lines.append(f"| {emoji} {sev} | {count} |")

    lines += [
        "",
        "---",
        "",
        "## 🎯 Findings",
        "",
    ]

    if not sorted_f:
        lines.append("_No significant findings recorded._")
    else:
        for i, finding in enumerate(sorted_f, 1):
            emoji = SEV_EMOJI.get(finding.severity.upper(), "•")
            lines += [
                f"### {i}. {emoji} [{finding.severity}] {finding.title}",
                "",
                f"**Severity:** `{finding.severity}`  ",
                f"**Discovered by:** `{finding.source_tool}`  ",
                "",
                f"{finding.detail}",
                "",
            ]

    lines += [
        "---",
        "",
        "## 🔍 Tools Executed",
        "",
        "| # | Tool | Status |",
        "|---|------|--------|",
    ]
    for i, t in enumerate(state.tools_run, 1):
        lines.append(f"| {i} | `{t}` | ✅ |")

    lines += [
        "",
        "---",
        "",
        "## 🛠️ Detected Services",
        "",
    ]
    if state.services:
        lines += [
            "| Port | Protocol | Service | Version |",
            "|-----:|:---------|:--------|:--------|",
        ]
        seen = set()
        for svc in state.services:
            key = (svc.get("port"), svc.get("service"))
            if key in seen:
                continue
            seen.add(key)
            lines.append(
                f"| {svc.get('port', '?')} | {svc.get('proto', '?')} "
                f"| {svc.get('service', '?')} | {svc.get('version', '?')} |"
            )
    else:
        lines.append("_No services parsed._")

    lines += [
        "",
        "---",
        "",
        "## ⚠️ Disclaimer",
        "",
        "> **This tool is for authorised security testing only.**  ",
        "> Always obtain written permission before scanning any target.  ",
        "> The authors accept no responsibility for misuse.",
        "",
        "---",
        "_Generated by PyKnock — https://github.com/you/pyknock_",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────
# JSON report
# ─────────────────────────────────────────────────────────────

def generate_json(state: AgentState) -> dict:
    elapsed = time.time() - state.start_time
    return {
        "meta": {
            "tool":    "pyknock",
            "version": "1.0.0",
            "target":  state.target,
            "date":    datetime.now(timezone.utc).isoformat(),
            "duration_s": round(elapsed, 1),
            "iterations": state.iterations,
            "tools_run":  state.tools_run,
        },
        "findings": [
            {
                "severity":    f.severity,
                "title":       f.title,
                "detail":      f.detail,
                "source_tool": f.source_tool,
            }
            for f in _sort_findings(state.findings)
        ],
        "services":   state.services,
        "open_ports": state.open_ports,
        "tool_results": [
            {
                "tool":    r["tool"],
                "command": r["command"],
                "success": r["success"],
                "stdout":  r["stdout"][:2000],
            }
            for r in state.tool_results
        ],
    }


# ─────────────────────────────────────────────────────────────
# Save both reports
# ─────────────────────────────────────────────────────────────

def save_reports(state: AgentState, output_dir: str = ".") -> tuple[str, str]:
    """Save markdown + JSON reports. Returns (md_path, json_path)."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_target = re.sub(r"[^\w\-.]", "_", state.target)

    md_path   = os.path.join(output_dir, f"pyknock_{safe_target}_{ts}.md")
    json_path = os.path.join(output_dir, f"pyknock_{safe_target}_{ts}.json")

    md_content   = generate_markdown(state)
    json_content = generate_json(state)

    with open(md_path, "w") as f:
        f.write(md_content)
    with open(json_path, "w") as f:
        json.dump(json_content, f, indent=2)

    return md_path, json_path


import re  # noqa: E402 (placed here to avoid circular at top)
